# Generated by Django 3.0.8 on 2020-07-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0002_auto_20200728_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
