# Generated by Django 3.0.8 on 2020-07-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('order_id', models.IntegerField(auto_created=True, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_email', models.EmailField(max_length=254, unique=True)),
                ('sender_address', models.CharField(max_length=64)),
                ('mission_name', models.CharField(max_length=32)),
                ('mission_data', models.TextField()),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '等待队列',
                'verbose_name_plural': '等待队列',
                'ordering': ['order_id'],
            },
        ),
    ]
