# Generated by Django 3.0.8 on 2020-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='account_email',
            field=models.EmailField(max_length=254),
        ),
    ]
