# Generated by Django 3.0.8 on 2020-07-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0003_historylist_runninglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historylist',
            name='using_time',
        ),
        migrations.AlterField(
            model_name='historylist',
            name='account_email',
            field=models.EmailField(max_length=254, verbose_name='账户邮箱'),
        ),
        migrations.AlterField(
            model_name='historylist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historylist',
            name='mission_data',
            field=models.TextField(verbose_name='任务详情'),
        ),
        migrations.AlterField(
            model_name='historylist',
            name='mission_name',
            field=models.CharField(max_length=32, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='historylist',
            name='register_time',
            field=models.DateTimeField(verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='historylist',
            name='sender_address',
            field=models.CharField(max_length=64, verbose_name='请求者地址'),
        ),
        migrations.AlterField(
            model_name='historylist',
            name='start_time',
            field=models.DateTimeField(verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='account_email',
            field=models.EmailField(max_length=254, verbose_name='账户邮箱'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='mission_data',
            field=models.TextField(verbose_name='任务详情'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='mission_name',
            field=models.CharField(max_length=32, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='register_time',
            field=models.DateTimeField(verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='sender_address',
            field=models.CharField(max_length=64, verbose_name='请求者地址'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='account_email',
            field=models.EmailField(max_length=254, verbose_name='账户邮箱'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='mission_data',
            field=models.TextField(verbose_name='任务详情'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='mission_name',
            field=models.CharField(max_length=32, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='order_id',
            field=models.IntegerField(auto_created=True, unique=True, verbose_name='队列ID'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='register_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='sender_address',
            field=models.CharField(max_length=64, verbose_name='请求者地址'),
        ),
    ]
