# Generated by Django 3.0.8 on 2020-07-29 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0004_auto_20200729_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylist',
            options={'verbose_name': '历史记录队列', 'verbose_name_plural': '历史记录队列'},
        ),
        migrations.AddField(
            model_name='historylist',
            name='used_time',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='用时'),
            preserve_default=False,
        ),
    ]
