# Generated by Django 3.0.8 on 2020-07-29 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0005_auto_20200729_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historylist',
            name='used_time',
        ),
    ]
