# Generated by Django 3.0.8 on 2020-07-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0006_remove_historylist_used_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryList',
        ),
    ]
