# Generated by Django 3.0.8 on 2020-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0007_delete_historylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(max_length=254, verbose_name='账户邮箱')),
                ('sender_address', models.CharField(max_length=64, verbose_name='请求者地址')),
                ('mission_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('mission_data', models.TextField(verbose_name='任务详情')),
                ('register_time', models.DateTimeField(verbose_name='注册时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('used_time', models.CharField(max_length=64, verbose_name='用时')),
            ],
            options={
                'verbose_name': '历史记录队列',
                'verbose_name_plural': '历史记录队列',
            },
        ),
    ]
