# Generated by Django 3.0.6 on 2020-08-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0008_historylist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historylist',
            options={'ordering': ['id'], 'verbose_name': '历史记录队列', 'verbose_name_plural': '历史记录队列'},
        ),
        migrations.AddField(
            model_name='historylist',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='队列ID'),
        ),
        migrations.AddField(
            model_name='runninglist',
            name='order_id',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='队列ID'),
        ),
        migrations.AddField(
            model_name='runninglist',
            name='used_time',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='用时'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='开始时间'),
        ),
        migrations.AddField(
            model_name='waitlist',
            name='used_time',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='用时'),
        ),
    ]
