# Generated by Django 3.0.6 on 2020-08-23 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0009_auto_20200816_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylist',
            name='exec_app',
            field=models.CharField(default='fluent191_solver', max_length=128, verbose_name='执行主流程'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runninglist',
            name='exec_app',
            field=models.CharField(default='fluent191_solver', max_length=128, verbose_name='执行主流程'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='exec_app',
            field=models.CharField(default='fluent191_solver', max_length=128, verbose_name='执行主流程'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historylist',
            name='mission_name',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='mission_name',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='mission_name',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='order_id',
            field=models.IntegerField(verbose_name='队列ID'),
        ),
    ]
