# Generated by Django 3.1 on 2020-08-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0010_waitlist_exec_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='historylist',
            name='exec_app',
            field=models.CharField(default='fluent_solver', max_length=128, verbose_name='执行主流程'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runninglist',
            name='exec_app',
            field=models.CharField(default='fluent_solver', max_length=128, verbose_name='执行主流程'),
            preserve_default=False,
        ),
    ]
