# Generated by Django 3.1 on 2020-08-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_queue', '0011_auto_20200820_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historylist',
            name='mission_name',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='runninglist',
            name='mission_name',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='mission_name',
            field=models.CharField(max_length=64, verbose_name='任务名称'),
        ),
    ]
